/* Cloudinary - secure document storage.
   Files are uploaded as type "authenticated": the delivery URL only works
   when it carries a valid signature generated by our server. The raw URL
   alone (if leaked) will not open the file. */
const { v2: cloudinary } = require("cloudinary");

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
  secure: true,
});

const FOLDER = "eduverify/documents";

function inferFormat(doc) {
  const fmt = String(doc?.file_format || "").toLowerCase().replace(/^\./, "");
  if (fmt) return fmt;
  const name = String(doc?.file_name || "").toLowerCase();
  const m = name.match(/\.([a-z0-9]+)$/i);
  return m ? m[1].toLowerCase() : "";
}

function resourceTypesFor(doc) {
  return [...new Set([doc?.file_resource_type, "image", "raw"].filter(Boolean))];
}

async function tryFetchUrl(url) {
  const resp = await fetch(url);
  if (!resp.ok) return null;
  const buf = Buffer.from(await resp.arrayBuffer());
  return buf.length > 0 ? buf : null;
}

/** Upload a file buffer to Cloudinary as an authenticated (signed) asset. */
function uploadBuffer(buffer, appNo, docCode) {
  return new Promise((resolve, reject) => {
    const stream = cloudinary.uploader.upload_stream(
      {
        folder: `${FOLDER}/${appNo}`,
        public_id: `${docCode}_${Date.now()}`,
        resource_type: "auto",
        type: "authenticated",
        overwrite: true,
      },
      (err, result) => (err ? reject(err) : resolve(result))
    );
    stream.end(buffer);
  });
}

/** Build a signed delivery URL for an authenticated asset. */
function signedUrl(doc, attachment = false) {
  if (!doc || !doc.file_public_id) return null;
  const resourceType = doc.file_resource_type || "image";
  const format = inferFormat(doc) || undefined;
  const expiresAt = Math.floor(Date.now() / 1000) + 3600;
  return cloudinary.utils.private_download_url(doc.file_public_id, format, {
    resource_type: resourceType,
    type: "authenticated",
    expires_at: expiresAt,
    attachment: attachment || undefined,
  });
}

/** Fetch a stored document's bytes (used to build bulk-download ZIPs). */
async function fetchAssetBuffer(doc) {
  if (!doc || !doc.file_public_id) return null;
  if (!isConfigured()) throw new Error("Document storage is not configured");

  const format = inferFormat(doc);
  const errors = [];

  for (const resourceType of resourceTypesFor(doc)) {
    try {
      const url = cloudinary.utils.private_download_url(doc.file_public_id, format, {
        resource_type: resourceType,
        type: "authenticated",
        expires_at: Math.floor(Date.now() / 1000) + 3600,
      });
      const buf = await tryFetchUrl(url);
      if (buf) return buf;
      errors.push(`private_download ${resourceType}: HTTP not ok`);
    } catch (e) {
      errors.push(`private_download ${resourceType}: ${e.message}`);
    }

    try {
      const url = cloudinary.url(doc.file_public_id, {
        type: "authenticated",
        resource_type: resourceType,
        format: format || undefined,
        secure: true,
        sign_url: true,
      });
      const buf = await tryFetchUrl(url);
      if (buf) return buf;
      errors.push(`signed_url ${resourceType}: HTTP not ok`);
    } catch (e) {
      errors.push(`signed_url ${resourceType}: ${e.message}`);
    }
  }

  for (const resourceType of ["image", "raw", "video"]) {
    try {
      const meta = await cloudinary.api.resource(doc.file_public_id, {
        resource_type: resourceType,
        type: "authenticated",
      });
      const fmt = meta.format || format;
      const url = cloudinary.utils.private_download_url(doc.file_public_id, fmt, {
        resource_type: resourceType,
        type: "authenticated",
        expires_at: Math.floor(Date.now() / 1000) + 3600,
      });
      const buf = await tryFetchUrl(url);
      if (buf) return buf;
    } catch (e) {
      errors.push(`api ${resourceType}: ${e.message}`);
    }
  }

  console.error("fetchAssetBuffer failed:", doc.doc_code, doc.file_public_id, errors.join("; "));
  throw new Error(`fetch failed for ${doc.doc_code}`);
}

/** Permanently delete a stored file (used when a student re-uploads). */
async function destroyAsset(publicId, resourceType) {
  if (!publicId) return;
  try {
    await cloudinary.uploader.destroy(publicId, {
      resource_type: resourceType || "image",
      type: "authenticated",
    });
  } catch (e) {
    console.warn("Cloudinary delete failed:", e.message);
  }
}

function isConfigured() {
  return !!(
    process.env.CLOUDINARY_CLOUD_NAME &&
    process.env.CLOUDINARY_API_KEY &&
    process.env.CLOUDINARY_API_SECRET
  );
}

module.exports = { cloudinary, uploadBuffer, signedUrl, fetchAssetBuffer, destroyAsset, isConfigured };
